name: Handle Repository Dispatch Event

on:
  repository_dispatch:
    types: [search-request]

jobs:
  run-search:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print search request
        run: |
          echo "Received search query: ${{ github.event.client_payload.query }}"

      - name: Run search (hypothetical action)
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -d '{"query": "${{ github.event.client_payload.query }}"}' \
            https://api.github.com/repos/fenetre-identification/Identification/actions/workflows/search.yml/dispatches
